version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=log-book
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    ports:
      - '9000:9000'
      - '8900:8900'
    volumes:
      - 'minio:/tmp/minio'
    command: 'minio server /tmp/minio --console-address ":8900"'

volumes:
  minio:
    driver: local
